#!/bin/bash
vlc -q --config vlcrc $RTSP_STREAM_URL & export VID_PID=$! && echo $VID_PID > ~/VID_PID 
#echo Video Player PID: `cat ~/VID_PID` \($VID_PID\)
echo `xdotool search --all --sync --onlyvisible --pid $VID_PID --name vlc | head -1` > ~/VID_WIN
#echo Video Player Window ID: `cat ~/VID_WIN` 
xdotool set_window --overrideredirect 0 `cat ~/VID_WIN`
xdotool windowunmap `cat ~/VID_WIN`
